### YamlMime:Certification
title: 'MCSE: Business Applications'
metadata:
  title: 'MCSE: Business Applications'
  description: 'MCSE: Business Applications'
uid: certification.mcse-business-applications
iconUrl: /media/learn/certification/badges/mcse-badge.svg
summary: |-
  <div>
  <div style='color&#58; red;'><strong>Als Reaktion auf die Situation mit dem Coronavirus (COVID-19) führt Microsoft mehrere vorübergehende Änderungen an unserem Schulungs- und Zertifizierungsprogramm durch. <a href='https://www.microsoft.com/en-us/learning/community-blog-post.aspx?BlogId=8&amp;Id=375289'>Mehr erfahren</a>.</strong><br/><br/></div>
  <div><strong>Diese Zertifizierung endet am 31. Januar 2021. Nach diesem Datum können Sie diese Zertifizierung nicht mehr erhalten. Alle Zertifizierungen, die Sie vor deren Ablaufen erhalten haben, werden weiterhin auf Ihrem Transkript im <a href='https://www.microsoft.com/learning/dashboard.aspx'>Zertifizierungs-Dashboard</a> angezeigt. Sie können auch <a href='/learn/certifications/retired-certifications'>alle abgelaufenen Zertifizierungen durchsuchen</a>.</strong><br/><br/></div>
  </div>

  Diese Zertifizierung bestätigt, dass Sie das Know-how haben, um mit Microsoft Dynamics 365 Technologien zu arbeiten und zu verwalten. Sie beginnen mit einer Grundlage in Microsoft Dynamics 365 und zeigen zusätzliche Expertise in einem oder mehreren geschäftsspezifischen Bereichen.

  Bestehen Sie eine der folgenden Prüfungen, um die MCSE&#58; Business Applications Zertifizierung zu erhalten&#58;
  - [MB2-716&#58; Microsoft Dynamics 365 Customization and Configuration](/learn/certifications/exams/mb2-716)
  - [MB2-718&#58; Microsoft Dynamics 365 for Customer Service](/learn/certifications/exams/mb2-718)
  - [MB2-719&#58; Microsoft Dynamics 365 for Marketing](/learn/certifications/exams/mb2-719)
  - [MB6-895&#58; Financial Management in Microsoft Dynamics 365 for Finance and Operations](/learn/certifications/exams/mb6-895)
  - [MB6-896&#58; Distribution and Trade in Microsoft Dynamics 365 for Finance and Operations](/learn/certifications/exams/mb6-896)
  - [MB6-897&#58; Microsoft Dynamics 365 for Retail](/learn/certifications/exams/mb6-897)
  - [MB6-898&#58; Microsoft Dynamics 365 for Talent](/learn/certifications/exams/mb6-898)
subTitle: Diese Zertifizierung bestätigt, dass Sie das Know-how haben, um mit Microsoft Dynamics 365 Technologien zu arbeiten und zu verwalten. Sie beginnen mit einer Grundlage in Microsoft Dynamics 365 und zeigen zusätzliche Expertise in einem oder mehreren geschäftsspezifischen Bereichen.
levels:
- beginner
skills:
- none
roles:
- business-analyst
type: mcse
products:
- dynamics
exams:
- uid: exam.mb-2-716
- uid: exam.mb-6-897
- uid: exam.mb-6-898
resources:
- title: Schulungs- und Zertifizierungsleitfaden
  description: Informieren Sie sich über die Zertifizierungen in einem übersichtlichen Schulungs- und Zertifizierungsleitfaden.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: Zertifizierungsposter
  description: Verschaffen Sie sich einen Überblick über die Grundlagen, aufgabenbasierte und fachliche Zertifizierungen.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: Exam Replay
  description: Sehen Sie sich zwei großartige Angebote an, die Ihnen helfen, Ihre Erfolgschancen zu erhöhen.
  href: deals.md
- title: Unterstützung von Zertifizierungen
  description: Erhalten Sie Hilfe in Microsoft Certification Support-Foren. Ein Forenmoderator wird Ihnen an einem Werktag (Montag-Freitag) antworten.
  href: help.md
- title: Zertifizierungsdashboard
  description: Überprüfen und verwalten Sie Ihre geplanten Termine, Zertifikate und Transkripte.
  href: https://www.microsoft.com/learning/dashboard.aspx

